# azure-pipelines.yml
trigger:
  - main

variables:
  namespace: 'azuredeploytest'
  helmChartPath: '$(System.DefaultWorkingDirectory)/hello-java-chart'
  releaseName: 'hello-java'
  javaAppPath: '$(System.DefaultWorkingDirectory)/target'

stages:
  - stage: Build
    displayName: 'Build Java Application'
    jobs:
      - job: BuildApp
        displayName: 'Build Java Application'
        pool:
          vmImage: 'ubuntu-latest'  # Microsoft-hosted agent with common tools
        steps:
          - task: Maven@3
            displayName: 'Build Java Application'
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'package'
              options: '-e'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '11'

          - task: CopyFiles@2
            displayName: 'Copy JAR to staging directory'
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)/target'
              Contents: '*.jar'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish JAR Artifact'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'java-app'
              publishLocation: 'Container'

  - stage: Deploy
    displayName: 'Deploy to Kubernetes'
    dependsOn: Build
    jobs:
      - job: DeployToK8s
        displayName: 'Deploy to Kubernetes Cluster'
        pool:
          vmImage: 'ubuntu-latest'  # Microsoft-hosted agent
        steps:
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'java-app'
              downloadPath: '$(System.ArtifactsDirectory)'

          - task: HelmDeploy@0
            displayName: 'Deploy Helm Chart'
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceConnection: 'K8s-AzureDeployTest'
              namespace: '$(namespace)'
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: '$(helmChartPath)'
              releaseName: '$(releaseName)'
              valueFile: '$(helmChartPath)/values/dev.yaml'
              overrideValues: |
                appVersion=$(Build.BuildId)
                ingress.hostname=$(releaseName).$(namespace).dev.oclc.org
                xlrelease_url=$(Build.BuildUri)
                technical_lead=$(Build.RequestedFor)
              waitForExecution: true
              arguments: '--timeout 5m'

          - script: |
              echo "Application deployed to: https://$(releaseName).$(namespace).dev.oclc.org"
              echo "Build ID: $(Build.BuildId)"
            displayName: 'Print Deployment Info'