# azure-pipelines.yml
trigger:
  - main

variables:
  namespace: 'azuredeploytest'
  helmChartPath: '$(System.DefaultWorkingDirectory)/hello-java-chart'
  releaseName: 'hello-java'
  powershellPath: 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'

stages:
  - stage: Build
    displayName: 'Build Java Application'
    jobs:
      - job: BuildApp
        displayName: 'Build Java Application'
        pool:
          name: 'Windows'
        steps:
          - task: CmdLine@2
            displayName: 'Setup PowerShell Path'
            inputs:
              script: |
                echo "Setting up PowerShell Path..."
                set PATH=%PATH%;C:\Windows\System32\WindowsPowerShell\v1.0
                echo %PATH%

          - task: Maven@3
            displayName: 'Build Java Application'
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'package'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '11'
              mavenVersionOption: 'Path'
              mavenPath: 'C:\Program Files\Apache\apache-maven-3.9.9'
              options: '-Dpowershell.path="C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe"'

          - task: CopyFiles@2
            displayName: 'Copy JAR to staging directory'
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)/target'
              Contents: '*.jar'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish JAR Artifact'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'java-app'
              publishLocation: 'Container'

  - stage: Deploy
    displayName: 'Deploy to Kubernetes'
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: DeployToK8s
        displayName: 'Deploy to Kubernetes Cluster'
        pool:
          name: 'Windows'
        steps:
          - task: CmdLine@2
            displayName: 'Setup PowerShell Path'
            inputs:
              script: |
                echo "Setting up PowerShell Path..."
                set PATH=%PATH%;C:\Windows\System32\WindowsPowerShell\v1.0
                echo %PATH%

          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'java-app'
              downloadPath: '$(System.ArtifactsDirectory)'

          - task: HelmDeploy@0
            displayName: 'Deploy Helm Chart'
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceConnection: 'Cluster_Connection'  # Correct service connection name
              namespace: '$(namespace)'
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: '$(helmChartPath)'
              releaseName: '$(releaseName)'
              valueFile: '$(helmChartPath)/values/dev.yaml'
              overrideValues: |
                image.repository=nginx
                image.tag=latest
                ingress.hostname=$(releaseName).$(namespace).dev.oclc.org
              waitForExecution: true
              arguments: '--timeout 5m'

          - script: |
              "$(powershellPath)" -Command "echo 'Application deployed to: https://$(releaseName).$(namespace).dev.oclc.org'"
            displayName: 'Print Deployment Info'