# azure-pipelines.yml
trigger:
  - main

variables:
  namespace: 'azuredeploytest'
  helmChartPath: '$(System.DefaultWorkingDirectory)/hello-java-chart'
  releaseName: 'hello-java'
  M2_HOME: 'C:\Program Files\Apache\apache-maven-3.9.9'
  MAVEN_HOME: 'C:\Program Files\Apache\apache-maven-3.9.9'

stages:
  - stage: Build
    displayName: 'Build Java Application'
    jobs:
      - job: BuildApp
        displayName: 'Build Java Application'
        pool:
          name: 'Windows'
        steps:
          - task: PowerShell@2
            displayName: 'Setup Maven Environment'
            inputs:
              targetType: 'inline'
              script: |
                Write-Host "Setting up Maven environment variables"
                echo "##vso[task.setvariable variable=M2_HOME]C:\Program Files\Apache\apache-maven-3.9.9"
                echo "##vso[task.setvariable variable=MAVEN_HOME]C:\Program Files\Apache\apache-maven-3.9.9"
                echo "##vso[task.setvariable variable=PATH]$env:PATH;C:\Program Files\Apache\apache-maven-3.9.9\bin"
                
                # Verify Maven is accessible
                try {
                    & "C:\Program Files\Apache\apache-maven-3.9.9\bin\mvn.cmd" -version
                    if ($LASTEXITCODE -eq 0) {
                        Write-Host "Maven is properly configured"
                    } else {
                        Write-Host "##vso[task.logissue type=warning]Maven command returned exit code $LASTEXITCODE"
                    }
                } catch {
                    Write-Host "##vso[task.logissue type=warning]Error running Maven: $_"
                }

          - task: Maven@3
            displayName: 'Build Java Application'
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'package'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '11'
              mavenVersionOption: 'Path'
              mavenPath: 'C:\Program Files\Apache\apache-maven-3.9.9'
              mavenSetM2Home: true

          - task: CopyFiles@2
            displayName: 'Copy JAR to staging directory'
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)/target'
              Contents: '*.jar'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish JAR Artifact'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'java-app'
              publishLocation: 'Container'

  - stage: Deploy
    displayName: 'Deploy to Kubernetes'
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: DeployToK8s
        displayName: 'Deploy to Kubernetes Cluster'
        pool:
          name: 'Windows'
        steps:
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'java-app'
              downloadPath: '$(System.ArtifactsDirectory)'

          - task: HelmDeploy@0
            displayName: 'Deploy Helm Chart'
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceConnection: 'Cluster_Connection'  # Correct service connection name
              namespace: '$(namespace)'
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: '$(helmChartPath)'
              releaseName: '$(releaseName)'
              valueFile: '$(helmChartPath)/values/dev.yaml'
              overrideValues: |
                image.repository=nginx
                image.tag=latest
                ingress.hostname=$(releaseName).$(namespace).dev.oclc.org
              waitForExecution: true
              arguments: '--timeout 5m'

          - script: |
              echo "Application deployed to: https://$(releaseName).$(namespace).dev.oclc.org"
            displayName: 'Print Deployment Info'
