# azure-pipelines.yml
trigger:
  - main

variables:
  namespace: 'azuredeploytest'
  helmChartPath: 'hello-java-chart'
  releaseName: 'hello-java'

stages:
  - stage: Build
    displayName: 'Build Java Application'
    jobs:
      - job: BuildApp
        displayName: 'Build Java Application'
        pool:
          name: 'Windows'
        steps:
          - task: CmdLine@2
            displayName: 'Fix PATH for System Tools'
            inputs:
              script: |
                @echo Setting up System PATH...
                set PATH=C:\Windows\System32;C:\Windows;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\wbem;C:\Program Files\Java\jdk-21.0.7\bin;C:\Program Files\Apache\apache-maven-3.9.9\bin;%PATH%
                @echo PATH is now: %PATH%

          # Add security scanning for Java code
          - task: MicrosoftSecurityDevOps@1
            displayName: 'Run Security Scan - Java Code'
            inputs:
              config: ''
              tools: 'bandit, eslint, java'
              # Optional: Add specific configurations for scanning
            continueOnError: true

          - task: Maven@3
            displayName: 'Build Java Application'
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'package'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'Path'
              jdkDirectory: 'C:\Program Files\Java\jdk-21.0.7'
              mavenVersionOption: 'Path'
              mavenPath: 'C:\Program Files\Apache\apache-maven-3.9.9'
              mavenSetM2Home: true

          - task: CopyFiles@2
            displayName: 'Copy JAR to staging directory'
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)/target'
              Contents: '*.jar'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'

          # Publish security scan results
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Security Scan Results'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/CodeAnalysisLogs'
              ArtifactName: 'SecurityScanResults'
              publishLocation: 'Container'
            condition: succeededOrFailed()

          - task: PublishBuildArtifacts@1
            displayName: 'Publish JAR Artifact'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'java-app'
              publishLocation: 'Container'

  # Add security scanning for Helm chart
  - stage: SecurityAnalyzeK8s
    displayName: 'Security Analysis - K8s Templates'
    jobs:
      - job: ScanK8sTemplates
        displayName: 'Scan Kubernetes Templates'
        pool:
          name: 'Windows'
        steps:
          - task: CmdLine@2
            displayName: 'Fix PATH for System Tools'
            inputs:
              script: |
                @echo Setting up System PATH...
                set PATH=C:\Windows\System32;C:\Windows;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\wbem;%PATH%

          # Run security scan on Helm chart
          - task: MicrosoftSecurityDevOps@1
            displayName: 'Scan Kubernetes Templates'
            inputs:
              config: ''
              tools: 'template-analyzer, kubesec'
              # Specific paths for Helm chart
              templateAnalyzerPath: '$(System.DefaultWorkingDirectory)/$(helmChartPath)/templates'
            continueOnError: true

          # Publish security scan results for K8s templates
          - task: PublishBuildArtifacts@1
            displayName: 'Publish K8s Security Scan Results'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/CodeAnalysisLogs'
              ArtifactName: 'K8sSecurityScanResults'
              publishLocation: 'Container'
            condition: succeededOrFailed()

  - stage: Deploy
    displayName: 'Deploy to Kubernetes'
    dependsOn:
      - Build
      - SecurityAnalyzeK8s
    condition: succeeded()
    jobs:
      - job: DeployToK8s
        displayName: 'Deploy to Kubernetes Cluster'
        pool:
          name: 'Windows'
        steps:
          - task: CmdLine@2
            displayName: 'Fix PATH for System Tools'
            inputs:
              script: |
                @echo Setting up System PATH...
                set PATH=C:\Windows\System32;C:\Windows;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\wbem;%PATH%

          - task: KubectlInstaller@0
            displayName: 'Install Kubectl'
            inputs:
              kubectlVersion: 'latest'

          - task: HelmInstaller@1
            displayName: 'Install Helm'
            inputs:
              helmVersionToInstall: 'latest'

          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'java-app'
              downloadPath: '$(System.ArtifactsDirectory)'

          # Download the kubeconfig file
          - task: DownloadSecureFile@1
            name: kubeconfig
            displayName: 'Download kubeconfig file'
            inputs:
              secureFile: 'k8s-devlab.yaml'

          # Deploy using the pre-created Helm chart
          - task: CmdLine@2
            displayName: 'Deploy Helm Chart with kubeconfig and insecure flag'
            inputs:
              script: |
                @echo Deploying Helm chart with kubeconfig and insecure-skip-tls-verify flag...
                
                @echo Running Helm upgrade command...
                helm upgrade --install $(releaseName) ./$(helmChartPath) ^
                  --namespace $(namespace) ^
                  --values ./$(helmChartPath)/values/dev.yaml ^
                  --set image.repository=bitnami/nginx,image.tag=latest,ingress.hostname=$(releaseName).$(namespace).dev.oclc.org ^
                  --wait --timeout 5m ^
                  --kubeconfig $(kubeconfig.secureFilePath) ^
                  --insecure-skip-tls-verify
                
                @echo Helm deployment command completed.

          - task: CmdLine@2
            displayName: 'Print Deployment Info'
            inputs:
              script: |
                @echo Application deployed to: https://$(releaseName).$(namespace).dev.oclc.org