# azure-pipelines.yml
trigger:
  - main

variables:
  namespace: 'azuredeploytest'
  helmChartPath: 'hello-java-chart'
  releaseName: 'hello-java'

stages:
  - stage: Build
    displayName: 'Build Java Application'
    jobs:
      - job: BuildApp
        displayName: 'Build Java Application'
        pool:
          name: 'Windows'
        steps:
          - task: CmdLine@2
            displayName: 'Fix PATH for System Tools'
            inputs:
              script: |
                @echo Setting up System PATH...
                set PATH=C:\Windows\System32;C:\Windows;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\wbem;C:\Program Files\Java\jdk-21.0.7\bin;C:\Program Files\Apache\apache-maven-3.9.9\bin;%PATH%
                @echo PATH is now: %PATH%

          - task: Maven@3
            displayName: 'Build Java Application'
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'package'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'Path'
              jdkDirectory: 'C:\Program Files\Java\jdk-21.0.7'
              mavenVersionOption: 'Path'
              mavenPath: 'C:\Program Files\Apache\apache-maven-3.9.9'
              mavenSetM2Home: true

          - task: CopyFiles@2
            displayName: 'Copy JAR to staging directory'
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)/target'
              Contents: '*.jar'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish JAR Artifact'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'java-app'
              publishLocation: 'Container'

  - stage: Deploy
    displayName: 'Deploy to Kubernetes'
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: DeployToK8s
        displayName: 'Deploy to Kubernetes Cluster'
        pool:
          name: 'Windows'
        steps:
          - task: CmdLine@2
            displayName: 'Fix PATH for System Tools'
            inputs:
              script: |
                @echo Setting up System PATH...
                set PATH=C:\Windows\System32;C:\Windows;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\wbem;%PATH%

          - task: KubectlInstaller@0
            displayName: 'Install Kubectl'
            inputs:
              kubectlVersion: 'latest'

          - task: HelmInstaller@1
            displayName: 'Install Helm'
            inputs:
              helmVersionToInstall: 'latest'

          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'java-app'
              downloadPath: '$(System.ArtifactsDirectory)'

          # Download the kubeconfig file
          - task: DownloadSecureFile@1
            name: kubeconfig
            displayName: 'Download kubeconfig file'
            inputs:
              secureFile: 'k8s-devlab.yaml'

          # Create a basic Helm chart since it's missing
          - task: CmdLine@2
            displayName: 'Create Helm Chart'
            inputs:
              script: |
                @echo Creating Helm chart directory structure...
                
                @echo Creating basic chart directory structure
                mkdir hello-java-chart
                mkdir hello-java-chart\templates
                mkdir hello-java-chart\values
                
                @echo Creating Chart.yaml
                echo apiVersion: v2 > hello-java-chart\Chart.yaml
                echo name: hello-java >> hello-java-chart\Chart.yaml
                echo description: A Helm chart for Hello Java application >> hello-java-chart\Chart.yaml
                echo type: application >> hello-java-chart\Chart.yaml
                echo version: 0.1.0 >> hello-java-chart\Chart.yaml
                echo appVersion: "1.0.0" >> hello-java-chart\Chart.yaml
                
                @echo Creating values.yaml
                echo replicaCount: 1 > hello-java-chart\values.yaml
                echo image: >> hello-java-chart\values.yaml
                echo   repository: nginx >> hello-java-chart\values.yaml
                echo   tag: latest >> hello-java-chart\values.yaml
                echo   pullPolicy: IfNotPresent >> hello-java-chart\values.yaml
                echo service: >> hello-java-chart\values.yaml
                echo   type: ClusterIP >> hello-java-chart\values.yaml
                echo   port: 80 >> hello-java-chart\values.yaml
                echo ingress: >> hello-java-chart\values.yaml
                echo   enabled: true >> hello-java-chart\values.yaml
                echo   hostname: hello-java.azuredeploytest.dev.oclc.org >> hello-java-chart\values.yaml
                
                @echo Creating dev values file
                copy hello-java-chart\values.yaml hello-java-chart\values\dev.yaml
                
                @echo Creating deployment.yaml
                echo apiVersion: apps/v1 > hello-java-chart\templates\deployment.yaml
                echo kind: Deployment >> hello-java-chart\templates\deployment.yaml
                echo metadata: >> hello-java-chart\templates\deployment.yaml
                echo   name: {{ .Release.Name }} >> hello-java-chart\templates\deployment.yaml
                echo spec: >> hello-java-chart\templates\deployment.yaml
                echo   replicas: {{ .Values.replicaCount }} >> hello-java-chart\templates\deployment.yaml
                echo   selector: >> hello-java-chart\templates\deployment.yaml
                echo     matchLabels: >> hello-java-chart\templates\deployment.yaml
                echo       app: {{ .Release.Name }} >> hello-java-chart\templates\deployment.yaml
                echo   template: >> hello-java-chart\templates\deployment.yaml
                echo     metadata: >> hello-java-chart\templates\deployment.yaml
                echo       labels: >> hello-java-chart\templates\deployment.yaml
                echo         app: {{ .Release.Name }} >> hello-java-chart\templates\deployment.yaml
                echo     spec: >> hello-java-chart\templates\deployment.yaml
                echo       containers: >> hello-java-chart\templates\deployment.yaml
                echo       - name: {{ .Release.Name }} >> hello-java-chart\templates\deployment.yaml
                echo         image: {{ .Values.image.repository }}:{{ .Values.image.tag }} >> hello-java-chart\templates\deployment.yaml
                echo         imagePullPolicy: {{ .Values.image.pullPolicy }} >> hello-java-chart\templates\deployment.yaml
                echo         ports: >> hello-java-chart\templates\deployment.yaml
                echo         - containerPort: 80 >> hello-java-chart\templates\deployment.yaml
                
                @echo Creating service.yaml
                echo apiVersion: v1 > hello-java-chart\templates\service.yaml
                echo kind: Service >> hello-java-chart\templates\service.yaml
                echo metadata: >> hello-java-chart\templates\service.yaml
                echo   name: {{ .Release.Name }} >> hello-java-chart\templates\service.yaml
                echo spec: >> hello-java-chart\templates\service.yaml
                echo   type: {{ .Values.service.type }} >> hello-java-chart\templates\service.yaml
                echo   ports: >> hello-java-chart\templates\service.yaml
                echo   - port: {{ .Values.service.port }} >> hello-java-chart\templates\service.yaml
                echo     targetPort: 80 >> hello-java-chart\templates\service.yaml
                echo   selector: >> hello-java-chart\templates\service.yaml
                echo     app: {{ .Release.Name }} >> hello-java-chart\templates\service.yaml
                
                @echo Creating ingress.yaml
                echo apiVersion: networking.k8s.io/v1 > hello-java-chart\templates\ingress.yaml
                echo kind: Ingress >> hello-java-chart\templates\ingress.yaml
                echo metadata: >> hello-java-chart\templates\ingress.yaml
                echo   name: {{ .Release.Name }} >> hello-java-chart\templates\ingress.yaml
                echo spec: >> hello-java-chart\templates\ingress.yaml
                echo   rules: >> hello-java-chart\templates\ingress.yaml
                echo   - host: {{ .Values.ingress.hostname }} >> hello-java-chart\templates\ingress.yaml
                echo     http: >> hello-java-chart\templates\ingress.yaml
                echo       paths: >> hello-java-chart\templates\ingress.yaml
                echo       - path: / >> hello-java-chart\templates\ingress.yaml
                echo         pathType: Prefix >> hello-java-chart\templates\ingress.yaml
                echo         backend: >> hello-java-chart\templates\ingress.yaml
                echo           service: >> hello-java-chart\templates\ingress.yaml
                echo             name: {{ .Release.Name }} >> hello-java-chart\templates\ingress.yaml
                echo             port: >> hello-java-chart\templates\ingress.yaml
                echo               number: {{ .Values.service.port }} >> hello-java-chart\templates\ingress.yaml
                
                @echo Chart structure created:
                dir hello-java-chart /s

          # Deploy with the newly created chart
          - task: CmdLine@2
            displayName: 'Deploy Helm Chart with kubeconfig and insecure flag'
            inputs:
              script: |
                @echo Deploying Helm chart with kubeconfig and insecure-skip-tls-verify flag...
                
                @echo Running Helm upgrade command...
                helm upgrade --install $(releaseName) ./$(helmChartPath) ^
                  --namespace $(namespace) ^
                  --values ./$(helmChartPath)/values/dev.yaml ^
                  --set image.repository=nginx,image.tag=latest,ingress.hostname=$(releaseName).$(namespace).dev.oclc.org ^
                  --wait --timeout 5m ^
                  --kubeconfig $(kubeconfig.secureFilePath) ^
                  --insecure-skip-tls-verify
                
                @echo Helm deployment command completed.

          - task: CmdLine@2
            displayName: 'Print Deployment Info'
            inputs:
              script: |
                @echo Application deployed to: https://$(releaseName).$(namespace).dev.oclc.org