replicaCount: 1
image:
  repository: bitnami/nginx
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  hostname: hello-java.azuredeploytest.dev.oclc.org
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi