
resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

# If you don't have these already, you might also want to add:
replicaCount: 1

image:
  repository: nginx  # This will be overridden by the workflow
  tag: latest        # This will be overridden by the workflow
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hostname: ""  # This will be set by the workflow